// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRepository(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddRepository'](arg1, arg2, arg3, arg4, arg5);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetAppDir() {
  return window['go']['main']['App']['GetAppDir']();
}

export function GetInstancesDir() {
  return window['go']['main']['App']['GetInstancesDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListRepositories() {
  return window['go']['main']['App']['ListRepositories']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenInstancesDir() {
  return window['go']['main']['App']['OpenInstancesDir']();
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function PingRepository(arg1) {
  return window['go']['main']['App']['PingRepository'](arg1);
}

export function RemoveRepository(arg1) {
  return window['go']['main']['App']['RemoveRepository'](arg1);
}

export function Restore() {
  return window['go']['main']['App']['Restore']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdateRepository(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateRepository'](arg1, arg2, arg3, arg4, arg5, arg6);
}
