// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repository} from '../models';
import {config} from '../models';

export function AddRepository(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:number):Promise<repository.Repository>;

export function Close():Promise<void>;

export function GetAppDir():Promise<string>;

export function GetInstancesDir():Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function ListRepositories():Promise<Array<repository.Repository>>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function OpenInstancesDir():Promise<void>;

export function PingAll():Promise<void>;

export function PingRepository(arg1:string):Promise<void>;

export function RemoveRepository(arg1:string):Promise<void>;

export function Restore():Promise<void>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function UpdateRepository(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:number):Promise<void>;
